"""Add original_requirements column to purchase_order table

Revision ID: add_original_requirements
Revises: add_transport_cost_column
Create Date: 2025-09-17 09:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_original_requirements'
down_revision = 'add_transport_cost'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('original_requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'original_requirements')
    # ### end Alembic commands ###
