"""Add delivery_type column to sales_order table

Revision ID: add_delivery_type
Revises: add_transport_cost
Create Date: 2025-09-10 14:16:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_delivery_type'
down_revision = 'add_transport_cost'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('delivery_type', sa.String(20), nullable=True, default='self'))
    # Set default value for existing records
    op.execute("UPDATE sales_order SET delivery_type = 'self' WHERE delivery_type IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'delivery_type')
    # ### end Alembic commands ###
