"""Add transport_cost column to sales_order table

Revision ID: add_transport_cost
Revises: add_sales_tables
Create Date: 2025-08-30 16:48:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_transport_cost'
down_revision = 'add_sales_tables_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order', sa.Column('transport_cost', sa.Float(), nullable=True, default=0.0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order', 'transport_cost')
    # ### end Alembic commands ###
